### PR TITLE
Added border drawing on android

### PR DESCRIPTION
**Pull request by ASloth**
Currently WIP

Using the bindable properties:
* BorderSize (double)
* BorderColor (Xamarin.Forms.Color)

### CODE REVIEW

**Comment by robinmanuelthiel** [comment]
Mh, so you added the border functionality on the platform level. That basically means that every platform has to implement something that could be done on a shared Xamarin.Forms level. I would prefer to see a Xamarin.Forms implementation for it.

**Comment by ASloth** [comment]
Implementing the drawing on a platform level is quite easy and similiar on all platforms + the performance should be better, thats why it was my first approach. Do you have an idea on how to implement this using only .Forms?

**Comment by robinmanuelthiel** [comment]
I was actually looking at kindof nesting the existing control into a parent "border" control that draws itself around the button. Something like this:

```xml
<Frame
    x:Name="Border"
    BackgroundColor="{Binding Source={x:Reference this}, Path=BorderColor}"
    CornerRadius="{Binding Source={x:Reference this}, Path=CornerRadius}"
    Padding="{Binding Source={x:Reference this}, Path=BorderThickness}"
    HasShadow="false">

    <Frame
        x:Name="Container"
        BackgroundColor="{Binding Source={x:Reference this}, Path=BackgroundColor}"
        CornerRadius="{Binding Source={x:Reference this}, Path=InnerCornerRadius}"
        HasShadow="false"
        Padding="0"
        Margin="0">

        <!-- ... ..>
    </Frame>
</Frame>
```

**Comment by robinmanuelthiel** [comment]
Gave it a first shot and am pretty happy with the result. What do you think?

image

**Comment by robinmanuelthiel** [comment]
As this is pure Xamarin.Forms, it will work across all platforms

**Comment by ASloth** [comment]
Looking good! I'm a bit afraid of nesting to many views having a negative performance impact, what do you think?

**Comment by robinmanuelthiel** [comment]
Legitimate point. Currently, we are nesting like this:

- Border (Frame)
  - Container (Frame)
    - ContainerContent (Grid)
      - Icon (Image)
      - Text (Label)

If `BorderThickness` is `0`, we could add the `CompressedLayout.IsHeadless = true` argument to it, which notifies Xamarin.Forms that now extra view is needed for it.

**Pull request closed without merging**
