### PR TITLE
Added FontAttributes, FontFamily and CommandParameter properties.

### PR DESCRIPTION
**Pull request by stormlion227**
Hello Robin

I've added **FontAttributes**, **FontFamily** and **CommandParameter**s properties.
I didn't update demo, because my XAML intelligence setting is different.

Thanks

### CODE REVIEW

**Comment by robinmanuelthiel** [comment]
Wow, great work! Thanks a lot!

**Comment by stormlion227** [comment]
Thanks for quick merge

**Comment by stormlion227** [comment]
When do you update nuget package? I'm waiting.

**Comment by robinmanuelthiel** [comment]
@stormlion227 I've just uploaded 0.7.0-pre for you :) Should be indexed and available within the next few hours. Be careful, it still has some bugs due to some changes in Xamarin.Forms 2.5.1

**Pull request merged**
