### PR TITLE
Enable CanExecute commanding

### PR DESCRIPTION
**Pull request by Depechie**
Initial draft for enabling CanExecute feature of commanding on the ClickedCommand.

Not done:

- Change color of button to visually indicate it's disabled
- Enabled property is not yet public available as a Bindable Property ( but this won't effect this CanExecute feature, so providing Enabled property can be a separate feature for the future )
- No test in the demo page, because even though code works; without the visual effect this is not yet finished

### CODE REVIEW

**Comment by robinmanuelthiel** [comment]
Great work, thanks a lot!

**Comment by robinmanuelthiel** [comment]
Just going through your code. Looks really good. Just one question: When do we need this, @Depechie?

```csharp
protected override void OnPropertyChanging([CallerMemberName] string propertyName = null)
{
    if (propertyName == ClickedCommandProperty.PropertyName)
    {
        ICommand cmd = ClickedCommand;
        if (cmd != null)
            cmd.CanExecuteChanged -= CommandCanExecuteChanged;
    }

    base.OnPropertyChanging(propertyName);
}
```

**Comment by Depechie** [comment]
@robinmanuelthiel to be honest, I 'would' assume that people using XAML will not 'detach' their commands. But you never know what people would do in code... so IF they somehow would like to NULL the command property, we clean up the event handler.

**Comment by Depechie** [comment]
Also when in code the command will change to a new command, we unhook before hooking up the new one.

**Comment by robinmanuelthiel** [comment]
Yep, the last argument convinced me, thanks for the clarification!

**Pull request merged**
