### PR TITLE
Update FlexButton.xaml.cs

### PR DESCRIPTION
**Pull request by ludocornut**
Adding IconOrientation.Top to set icon on top of text.

### CODE REVIEW

**Comment by ludocornut** [comment]
I forget to commit IconOrientation.cs :
public enum IconOrientation
    {
        Top,
        Left,
        Right
    }

**Comment by robinmanuelthiel** [comment]
Nice addition, I like it! Thank you very much!

**Comment by Symorp** [comment]
Hello,
is this change on nugget repo? When I try t set IconOrientation=Top in xaml it doesn't position icon on top.

**Comment by robinmanuelthiel** [comment]
Should be in v0.11.0 https://github.com/robinmanuelthiel/flexbutton/releases/tag/v0.11.0
Please file an issue, if it doesn't work!

**Pull request merged**
